//! Rojo-style filesystem projection for working on place scripts in Android editors.
use rbx_dom_weak::{types::Ref, WeakDom};
use serde::Serialize;
use std::collections::HashMap;

use crate::rbxl;

#[derive(Serialize)]
struct ProjectBundle { name: String, files: Vec<ProjectFile> }
#[derive(Serialize)]
struct ProjectFile { path: String, content: String }

pub fn build_bundle<'a>(dom: &WeakDom, name: &str, overrides: impl IntoIterator<Item=(Ref, &'a str)>) -> String {
    let overrides: HashMap<Ref, &str> = overrides.into_iter().collect();
    let project_name = sanitize(name).trim_matches('_').to_string();
    let project_name = if project_name.is_empty() { "RobloxProject".into() } else { project_name };
    let mut files = Vec::new();
    walk(dom, dom.root_ref(), &mut Vec::new(), &mut files, &overrides);
    files.push(ProjectFile { path: "default.project.json".into(), content: format!(
        "{{\n  \"name\": {},\n  \"tree\": {{ \"$className\": \"DataModel\", \"$path\": \"src\" }}\n}}\n",
        serde_json::to_string(&project_name).unwrap_or_else(|_| "\"RobloxProject\"".into())) });
    files.push(ProjectFile { path: ".luaurc".into(), content:
        "{\n  \"languageMode\": \"strict\",\n  \"lint\": { \"UnusedVariable\": true },\n  \"aliases\": {\n    \"src\": \"./src\",\n    \"shared\": \"./src/ReplicatedStorage\"\n  }\n}\n".into() });
    files.push(ProjectFile { path: "README.md".into(), content:
        "# Roblox Luau project\n\nGenerated by Android RBXL Editor. Open this folder in Xed or another Android editor. Return to RBXL Editor to import changed `.luau` files. Use `@src/...`, `@shared/...`, relative paths, or `@self` in string requires.\n".into() });
    serde_json::to_string(&ProjectBundle { name: project_name, files }).unwrap_or_default()
}

fn walk(dom: &WeakDom, referent: Ref, path: &mut Vec<String>, files: &mut Vec<ProjectFile>, overrides: &HashMap<Ref, &str>) {
    let Some(instance) = dom.get_by_ref(referent) else { return };
    if referent != dom.root_ref() { path.push(sanitize(instance.name.as_str())); }
    if matches!(instance.class.as_str(), "Script" | "LocalScript" | "ModuleScript") {
        let suffix = match instance.class.as_str() { "Script" => ".server.luau", "LocalScript" => ".client.luau", _ => ".luau" };
        files.push(ProjectFile { path: format!("src/{}{}", path.join("/"), suffix), content:
            overrides.get(&referent).map(|v| (*v).to_string()).unwrap_or_else(|| rbxl::get_source(dom, referent).unwrap_or_default()) });
    }
    for &child in instance.children() { walk(dom, child, path, files, overrides); }
    if referent != dom.root_ref() { path.pop(); }
}

/// Match an exported file path back to its script and return source updates.
pub fn decode_sync(dom: &WeakDom, json: &str) -> Result<Vec<(Ref, String)>, String> {
    let value: serde_json::Value = serde_json::from_str(json).map_err(|e| e.to_string())?;
    let mut paths = HashMap::new();
    collect_paths(dom, dom.root_ref(), &mut Vec::new(), &mut paths);
    let mut updates = Vec::new();
    for file in value.get("files").and_then(|v| v.as_array()).ok_or("missing files")? {
        if let (Some(path), Some(content)) = (file.get("path").and_then(|v| v.as_str()), file.get("content").and_then(|v| v.as_str())) {
            if let Some(&referent) = paths.get(path) { updates.push((referent, content.to_string())); }
        }
    }
    Ok(updates)
}

fn collect_paths(dom: &WeakDom, referent: Ref, path: &mut Vec<String>, out: &mut HashMap<String, Ref>) {
    let Some(instance) = dom.get_by_ref(referent) else { return };
    if referent != dom.root_ref() { path.push(sanitize(instance.name.as_str())); }
    let suffix = match instance.class.as_str() { "Script" => Some(".server.luau"), "LocalScript" => Some(".client.luau"), "ModuleScript" => Some(".luau"), _ => None };
    if let Some(suffix) = suffix { out.insert(format!("src/{}{}", path.join("/"), suffix), referent); }
    for &child in instance.children() { collect_paths(dom, child, path, out); }
    if referent != dom.root_ref() { path.pop(); }
}

fn sanitize(value: &str) -> String {
    let cleaned: String = value.chars().map(|c| if c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.') { c } else { '_' }).collect();
    if cleaned.is_empty() { "unnamed".into() } else { cleaned }
}
